article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('', views.articles, name = "articles"),
    path('dashboard/',views.dashboard, name = "dashboard"),
    path('addarticle/',views.addarticle, name="addarticle"),
    path('article/<int:id>',views.detail, name="detail"),
    path('update/<int:id>',views.updatearticle, name="updatearticle"),
    path('delete/<int:id>',views.deletearticle, name="deletearticle"),
    path('error/',views.hata, name="hata"),
    path('article/comment/<int:id>',views.articleComment, name="articlecomment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name="index"),
    path('about/',views.about, name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.user", on_delete=models.CASCADE, verbose_name="Yazar")
    title = models.CharField(max_length=50,verbose_name="Başlık")
    content = RichTextField(verbose_name="İçerik")   
    created_time = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank=True, null=True, verbose_name="Görsel Ekle")

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_time']
    
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="Makale", related_name="comments")
    comment_author = models.CharField(max_length=50, verbose_name="İsim")
    comment_content = RichTextField(max_length=200, verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True, verbose_name="Tarih")

    def __str__(self):
        return self.comment_author
    
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django.forms import ModelForm
from .models import Article

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]
        

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.conf import settings
# Create your views here.

#Anasayfa
def index(request):
    return render(request,"index.html")

#Hakkında
def about(request):
    return render(request,"about.html")

#Makaleler
def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request, "articles.html", {"articles":articles})
    articles = Article.objects.all()
    return render(request, "articles.html", {"articles":articles})

#Dashboard
@login_required(login_url="article:hata")
def dashboard(request):
        articles = Article.objects.filter(author = request.user)
        return render(request,"dashboard.html",{"articles":articles})

#Makale Ekleme
@login_required(login_url="article:hata")
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale başarılı bir şekilde eklendi.")
        return redirect("article:dashboard")
    return render(request,"addarticle.html",{"form":form})

#Makale Detay Sayfası
def detail(request,id):
    article = get_object_or_404(Article, id=id)
    
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article, "comments":comments})

# Makale Güncelle
@login_required(login_url="article:hata")
def updatearticle(request,id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if article.author == request.user:
        if form.is_valid():
            form.save(commit=False)
            article.author = request.user
            article.save()
            messages.success(request, "Makale başarılı bir şekilde güncellendi.")
            return redirect("article:dashboard")
        return render(request, "updatearticle.html", {"form":form})
    else:
        messages.error(request, "Yetkisiz İşlem")
        return redirect("article:dashboard")

#Makale Silme
@login_required(login_url="article:hata")
def deletearticle(request,id):
    article = get_object_or_404(Article, id=id)
    if article.author == request.user:
        article.delete()
        messages.success(request, "Makale başarılı bir şekilde silindi.")
        return redirect("article:dashboard")
    else:
        messages.error(request, "Yetkisiz İşlem")
        return redirect("article:dashboard")

def hata(request):
    messages.error(request, "Yetkisiz İşlem!")
    return redirect("index")

def articleComment(request,id):
    article = get_object_or_404(Article, id=id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article
        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":id}))
    
 

templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>Hakkımızda</h3>
<hr>
<p>
Mertok Yazılım 2008 yılında yazılım dünyasına yeni bir soluk kazandırmak ve bu dünyadaki
gelişmeleri takip ederek en güncel bilgileri ve geçmişte edinilen deneyimleri aktarmak için kuruldu.
</p>
<hr>
{% endblock %}

templates/addarticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Ekle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}} <br>
            <button type="submit" class="btn btn-primary">Gönder</button>
        </form>
    </div>
</div>

{% endblock %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class="row">
  <div class="col-md-10 offset-md-1">
      <h3>Makaleler</h3>
      <hr>
  </div>
</div>

<div class="row">
  <div class="col-md-10 offset-md-1">
      <form>
        {% csrf_token %}
        <input type="text" name="keyword" class="form-control" placeholder="Makale Ara"/>
        <button type="submit" class="btn btn-primary btn-sm" style="margin-top:10px;">Ara</button>
      </form>
  </div>
</div>

{% if articles %}
<div class="row">
  <div class="col-md-10 offset-md-1">
    <table style="margin-top: 20px;" class="table table-hover">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Başlık</th>
          <th scope="col">Yazar</th>
          <th scope="col">Oluşturulma Tarihi</th>
        </tr>
      </thead>
      <tbody>
      {% for article in articles %}
      <tr>
          <th scope="row">{{article.id}}</th>
          <td>
            <a href="{% url 'article:detail' article.id %}"><strong>{{article.title}}</strong></a><br>
            {{article.content|safe|truncatewords:20}}
            <a href="{% url 'article:detail' article.id %}">Devamını Oku</a>
          </td>
          <td>{{article.author.username}}</td>
          <td>{{article.created_time}}</td>
      </tr>
      </tbody>
      {% endfor %}
  </table>
  </div>
</div>



{% else %}
<div class="alert alert-danger">Makale Bulunmuyor!</div>
{% endif %}


{% endblock %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<p>
    <small>Hoşgeldiniz {{request.user.username}}</small>
</p>
<hr>
<a href="/articles/addarticle" class="btn btn-danger">Makale Ekle</a>
<br> <br>

{% if articles %}

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Oluşturulma Tarihi</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
        {% for article in articles %}
      <tr>
        <th scope="row">{{article.id}}</th>
        <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
        <td>{{article.author.username}}</td>
        <td>{{article.created_time}}</td>
        <td><a href="{% url 'article:updatearticle' article.id %}" class="btn btn-primary">Güncelle</a></td>
        <td><a href="{% url 'article:deletearticle' article.id %}" class="btn btn-danger">Sil</a></td>
      </tr>
    </tbody>
    {% endfor %}
</table>
{% else %}
<div class="alert alert-danger">Henüz bir makaleniz bulunmuyor.</div>
{% endif %}
{% endblock %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Article Title -->
                    <h3 class="fw-bolder mb-1">{{article.title}}</h3> <br>
                    <!--Author-->
                    <p class="mb-1">
                        {{article.author.username}} 
                    </p>
                    <!-- Post meta content-->
                    <p class="mb-3">
                    <small>{{article.created_time}}</small>
                    <hr>
                </p>
                </header>
                <!-- Preview image figure-->
                {% if article.article_image%}
                <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
                {% endif %}
                
                <!-- Post content-->
                <p class="mb-1">
                    {{article.content|safe}}
                </p>
                <hr>
            </article>

            <h4>Yorumlar</h4> <hr>

            {% if comments %}
            {% for comment in comments %}
            
            <div class="d-flex">
                <div class="flex-shrink-0">
                    <img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />
                </div>
                <div class="ms-3">
                    <div class="fw-bold">
                        {{comment.comment_author}} <br>
                        <small>{{comment.comment_date}}</small> <br>
                    </div>
                    <p style="margin-top: 10px;">
                    {{comment.comment_content}} 
                    </p>
                    <hr>
                </div>
            </div>
            
            {% endfor %}
            {% else %}
            <div class="alert alert-info">
                Henüz Yorum Yapılmamış. İlk Yorum Yapan Siz Olun.
            </div>
            {% endif %}
            
    
            <div class="card my-5">
                <h5 class="card-header">Yorum Ekle</h5>
                <div class="card-body">
                    <form method="post" action="{% url 'article:articlecomment' article.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="formGroupExampleInput">İsim</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" name="comment_author" placeholder="İsminizi yazın">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput2">Yorum</label>
                            <input type="text" class="form-control" id="formGroupExampleInput2" name="comment_content" placeholder="Yorumunuzu yazın">
                        </div>
                        <button type="submit" class="btn btn-primary">Gönder</button>
                    </form>
                </div>
            </div>
           
        </div>
    </div
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
<div class="jumbotron text-center">
    <h3>Mertok Yazılım'a Hoşgeldiniz</h3>
    <p>
        Bu blogda yazılım dünyası ile ilgili son gelişmeleri bulabilir
        kafanıza takılan soruları forum genelinde tartışabilirsiniz.
    </p>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Mertok Yazılım</title>
</head>
<body>
    {% include "includes/navbar.html" %}
    <div style="margin-top: 100px; margin-bottom: 100px;" class="container">
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
            {% if message.tags == "error" %}
            <div class="alert alert-danger">{{ message }}</div>>
            {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
            {% endfor %}
        {% endif %}

        {% block body %}
    
        {% endblock %}
    </div>


    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{form|crispy}} <br>
            <button type="submit" class="btn btn-primary">Giriş Yap</button>
        </form>
    </div>
</div>
    

{% endblock %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{form|crispy}} <br>
            <button type="submit" class="btn btn-primary">Kayıt Ol</button>
        </form>
    </div>
</div>

{% endblock %}

templates/updatearticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}} <br>
            <button type="submit" class="btn btn-primary">Güncelle</button>
        </form>
    </div>
</div>

{% endblock %}